server:
  #tomcat运行端口
  port: 9999

spring:
  profiles:
    active: local
  application:
      name: api-gateway
  http:
      encoding:
        force: false
        enabled: true
        charset: utf-8
      multipart:
        #默认支持文件上传
        enabled: true
        #支持文件写入磁盘
        file-size-threshold: 0
        # 最大支持文件大小
        max-file-size: 100Mb
        # 最大支持请求大小
        max-request-size: 100Mb


#拦截器排除拦截路径(方法)
authIgnoreUri:
  - /user/userAccount/login
  - /home/uploadFile/uploadImage

