# 注册到eureka-server上
eureka:
  client:
    # 是否将eureka自身作为应用注册到eureka注册中心
    register-with-eureka: false
    # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: true
    # 设置拉取服务注册信息时间（缺省为60s）
    registry-fetch-interval-seconds: 5
    # Eureka服务
    serviceUrl:
      #服务注册中心地址
      defaultZone: http://127.0.0.1:8000/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#网关配置
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  max:
    host:
      # 并发处理数，值越大越好，但到到达一个临界点之后，就不会提高响应速度了
      connections:  500
  host:
    # 连接时间semaphores
    connect-timeout-millis: 60000
  #路由配置
  routes:
    user:
      #代理接口路径
      path: /user/**
      serviceId: user-api
      #是否带当前前缀,true:不带，false:不带
      stripPrefix: true
    admin:
      #代理接口路径
      path: /admin/**
      serviceId: admin-api
      #是否带当前前缀,true:不带，false:不带
      stripPrefix: true





