eureka:
  instance:
    #当前实例的主机名称
    hostname: 127.0.0.1
  client:
    #是否将eureka自身作为应用注册到eureka注册中心
    register-with-eureka: false
    #客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
    #Eureka服务
    serviceUrl:
      #服务注册中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭自我保护模式（缺省为打开）
    enable-self-preservation: false
    #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000